### PR TITLE
Update actions.md: correct UpdateMSU options

### PR DESCRIPTION
**Pull request by iamacarpet**
The example for `UpdateMSU` in the docs is misleading.

The option need to be an array of updates, each itself an array of arguments.

### CODE REVIEW

**Review by TsekNet — CHANGES_REQUESTED** [review]
Nit: Can you move each list argument to it's own line to make it easier for humans to read?

**Comment by TsekNet** [comment]
ping @iamacarpet

**Comment by iamacarpet** [comment]
Sorry @TsekNet , I'll get this sorted.

**Comment by iamacarpet** [comment]
There we go @TsekNet ,

I hope you don't mind me also documenting the argument list, as I found myself having to dive into the code again to confirm the hash format (until I realised I could guess it from the hash length, but that isn't the point) :).

**Pull request merged**
